[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { path = "../lib/utils" }
freelancers = { path = "../lib/freelancers" }
clients = { path = "../lib/clients" }
authentication = { path = "../lib/authentication" }
reviews = { path = "../lib/reviews" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8.6", features = ["postgres", "chrono", "runtime-tokio"] }
axum = { version = "0.8.7", features = ["macros"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
dotenv = "0.15.0"
dotenvy = "0.15.0"